import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useCallback, useEffect } from 'react'
import { tokenize } from "kuromojin"

const kanaToHira = (str: string) => str.replace(/[\u30a1-\u30f6]/g, (match) => String.fromCharCode(match.charCodeAt(0) - 0x60));

const Home: NextPage = () => {
  const [text, setText] = useState('');
  const [yomi, setYomi] = useState('');
  
  const handleChange = useCallback((event) => {
    setText(event.target.value);
  }, [])

  useEffect(
    () => {
      tokenize(text).then((tokens) => {
        setYomi(kanaToHira(tokens.filter((token) => !!token.reading).map((token) => token.reading).join('')));
      });
    }, [text]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>
          <label>入力値:</label>
          {text}
        </p>
        <p>
          <label>よみがな:</label>
          {yomi}
        </p>
        <input type="text" value={text} onChange={handleChange} />
      </div>
    </div>
  )
}

export default Home
